name: build

on:
  pull_request:

  push:
    branches:
      - main
    tags:
      - v*

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            go: 1.19

          - os: ubuntu-latest
            go: 1.x

          - os: macos-latest
            go: 1.x

    name: "${{ matrix.os }} / go ${{ matrix.go }}"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: make build

      - name: Run tests
        run: make test
